name = "metatablesnow/deep_delta"
version = "3.0.4"
description = "Unofficial port of DeepDelta 3.0.4 to Pesde."
repository = "https://github.com/metatablesnow/DeepDelta/tree/main"
authors = ["Sona"]
licence = "MIT"
includes = ["pesde.toml", "LICENSE", "README.md", "src/**"]

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"